.TH "src/header/diskdevice.h" 3 "Tue May 25 2021" "OpenFSL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/header/diskdevice.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include 'sector\&.h'\fP
.br
\fC#include 'vint\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBopenFSL::DiskDevice\fP"
.br
.RI "Disk driver\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBopenFSL\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDISKDEV_ERROR_SUCCESS\fP   0x0"
.br
.ti -1c
.RI "#define \fBDISKDEV_ERROR_NOT_INITIALIZED\fP   0x01"
.br
.ti -1c
.RI "#define \fBDISKDEV_ERROR_INIT_NOFUNC\fP   0x02"
.br
.ti -1c
.RI "#define \fBDISKDEV_ERROR_DISK_ERROR\fP   0x03"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DISKDEV_ERROR_DISK_ERROR   0x03"

.SS "#define DISKDEV_ERROR_INIT_NOFUNC   0x02"

.SS "#define DISKDEV_ERROR_NOT_INITIALIZED   0x01"

.SS "#define DISKDEV_ERROR_SUCCESS   0x0"

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenFSL from the source code\&.
