.TH "src/fs_fat32/fat32_dir.cpp" 3 "Tue May 25 2021" "OpenFSL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fs_fat32/fat32_dir.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./header/fs_fat32/fs_fat32\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "uint8_t * \fBstr16to8\fP (uint8_t *dest, const uint16_t *src, size_t size)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "uint8_t* str16to8 (uint8_t * dest, const uint16_t * src, size_t size)"

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenFSL from the source code\&.
