.TH "src/header/fslservices.h" 3 "Tue May 25 2021" "OpenFSL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/header/fslservices.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'stddef\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBopenFSL\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBopenFSL::initializeLibrary\fP ()"
.br
.RI "Library initializer\&. "
.ti -1c
.RI "void \fBopenFSL::fsl_strtokenize\fP (const std::string &str, std::vector< std::string > &tokens, const std::string &delimiters)"
.br
.RI "String tokenizer\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenFSL from the source code\&.
