.TH "openFSL::fileInfoStruct" 3 "Tue May 25 2021" "OpenFSL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
openFSL::fileInfoStruct \- FAT32 file information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fs_fat32\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBfileName\fP"
.br
.ti -1c
.RI "uint8_t \fBfileAttr\fP"
.br
.ti -1c
.RI "\fBFAT32_fileInfoTime\fP \fBfileCreateTime\fP"
.br
.ti -1c
.RI "\fBFAT32_fileInfoTime\fP \fBfileAccessTime\fP"
.br
.ti -1c
.RI "\fBFAT32_fileInfoTime\fP \fBfileModTime\fP"
.br
.ti -1c
.RI "uint32_t \fBfileLocation\fP"
.br
.ti -1c
.RI "uint32_t \fBfileSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
FAT32 file information\&. 


.PP
\fBAuthor\fP
.RS 4
kms1212
.RE
.PP
Type Name  std::string fileName  uint8_t fileAttr  FAT32_fileInfoTime fileCreateTime  FAT32_fileInfoTime fileAccessTime  FAT32_fileInfoTime fileModTime  uint32_t fileLocation  uint32_t fileSize  
.PP
Definition at line 259 of file fs_fat32\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFAT32_fileInfoTime\fP openFSL::fileInfoStruct::fileAccessTime"

.PP
Definition at line 263 of file fs_fat32\&.h\&.
.SS "uint8_t openFSL::fileInfoStruct::fileAttr"

.PP
Definition at line 261 of file fs_fat32\&.h\&.
.SS "\fBFAT32_fileInfoTime\fP openFSL::fileInfoStruct::fileCreateTime"

.PP
Definition at line 262 of file fs_fat32\&.h\&.
.SS "uint32_t openFSL::fileInfoStruct::fileLocation"

.PP
Definition at line 265 of file fs_fat32\&.h\&.
.SS "\fBFAT32_fileInfoTime\fP openFSL::fileInfoStruct::fileModTime"

.PP
Definition at line 264 of file fs_fat32\&.h\&.
.SS "std::string openFSL::fileInfoStruct::fileName"

.PP
Definition at line 260 of file fs_fat32\&.h\&.
.SS "uint32_t openFSL::fileInfoStruct::fileSize"

.PP
Definition at line 266 of file fs_fat32\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenFSL from the source code\&.
