.TH "openFSL::fileTimeStruct" 3 "Tue May 25 2021" "OpenFSL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
openFSL::fileTimeStruct \- FAT32 time\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fs_fat32\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBtime_tenth\fP"
.br
.ti -1c
.RI "uint8_t \fBtime_sec\fP"
.br
.ti -1c
.RI "uint8_t \fBtime_min\fP"
.br
.ti -1c
.RI "uint8_t \fBtime_hour\fP"
.br
.ti -1c
.RI "uint8_t \fBtime_day\fP"
.br
.ti -1c
.RI "uint8_t \fBtime_month\fP"
.br
.ti -1c
.RI "uint16_t \fBtime_year\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
FAT32 time\&. 


.PP
\fBAuthor\fP
.RS 4
kms1212
.RE
.PP
Type Name  uint8_t time_tenth  uint8_t time_sec  uint8_t time_min  uint8_t time_hour  uint8_t time_day  uint8_t time_month  uint16_t time_year  
.PP
Definition at line 133 of file fs_fat32\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t openFSL::fileTimeStruct::time_day"

.PP
Definition at line 138 of file fs_fat32\&.h\&.
.SS "uint8_t openFSL::fileTimeStruct::time_hour"

.PP
Definition at line 137 of file fs_fat32\&.h\&.
.SS "uint8_t openFSL::fileTimeStruct::time_min"

.PP
Definition at line 136 of file fs_fat32\&.h\&.
.SS "uint8_t openFSL::fileTimeStruct::time_month"

.PP
Definition at line 139 of file fs_fat32\&.h\&.
.SS "uint8_t openFSL::fileTimeStruct::time_sec"

.PP
Definition at line 135 of file fs_fat32\&.h\&.
.SS "uint8_t openFSL::fileTimeStruct::time_tenth"

.PP
Definition at line 134 of file fs_fat32\&.h\&.
.SS "uint16_t openFSL::fileTimeStruct::time_year"

.PP
Definition at line 140 of file fs_fat32\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenFSL from the source code\&.
