.TH "openFSL::Sector" 3 "Tue May 25 2021" "OpenFSL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
openFSL::Sector \- \fBSector\fP buffer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sector\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSector\fP (size_t sector_count_, uint32_t bytespersector)"
.br
.RI "\fBSector\fP class constructor\&. "
.ti -1c
.RI "\fB~Sector\fP ()"
.br
.RI "\fBSector\fP class destructor\&. "
.ti -1c
.RI "vint_arch \fBgetSectorCount\fP ()"
.br
.RI "\fBSector\fP count getter\&. "
.ti -1c
.RI "uint8_t * \fBgetData\fP ()"
.br
.RI "Data buffer getter\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBSector\fP buffer\&. 

\fBSector\fP buffer with uint8_t(byte) array\&. 
.PP
\fBAuthor\fP
.RS 4
kms1212 
.RE
.PP
\fBTodo\fP
.RS 4
Change buffer addressing process
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Sector::Sector (size_t sector_count_, uint32_t bytespersector)"

.PP
\fBSector\fP class constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIsector_count_\fP \fBSector\fP count 
.br
\fIbytespersector\fP Bytes per sector 
.RE
.PP

.SS "Sector::~Sector ()"

.PP
\fBSector\fP class destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "uint8_t * Sector::getData ()"

.PP
Data buffer getter\&. 
.PP
\fBReturns\fP
.RS 4
uint8_t*: Data buffer pointer 
.RE
.PP

.SS "uint64_t Sector::getSectorCount ()"

.PP
\fBSector\fP count getter\&. 
.PP
\fBReturns\fP
.RS 4
vint_arch: \fBSector\fP count 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for OpenFSL from the source code\&.
