.TH "openFSL::fatFSINFOStruct" 3 "Tue May 25 2021" "OpenFSL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
openFSL::fatFSINFOStruct \- FAT32 FSINFO structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fs_fat32\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBfsinfoSignature1\fP"
.br
.ti -1c
.RI "uint8_t \fBfsinfoReserved1\fP [480]"
.br
.ti -1c
.RI "uint32_t \fBfsinfoSignature2\fP"
.br
.ti -1c
.RI "uint32_t \fBfsinfoFreeCluster\fP"
.br
.ti -1c
.RI "uint32_t \fBfsinfoNextFree\fP"
.br
.ti -1c
.RI "uint8_t \fBfsinfoReserved2\fP [12]"
.br
.ti -1c
.RI "uint32_t \fBfsinfoSignature3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
FAT32 FSINFO structure\&. 


.PP
\fBAuthor\fP
.RS 4
kms1212
.RE
.PP
Type Name Offset  uint32_t fsinfoSignature1 0x0000  uint8_t fsinfoReserved1[480] 0x0004  uint32_t fsinfoSignature2 0x01E4  uint32_t fsinfoFreeCluster 0x01E8  uint32_t fsinfoNextFree 0x01EC  uint8_t fsinfoReserved2[12] 0x01F0  uint32_t fsinfoSignature3 0x01FE  
.SH "Member Data Documentation"
.PP 
.SS "uint32_t openFSL::fatFSINFOStruct::fsinfoFreeCluster"

.SS "uint32_t openFSL::fatFSINFOStruct::fsinfoNextFree"

.SS "uint8_t openFSL::fatFSINFOStruct::fsinfoReserved1[480]"

.SS "uint8_t openFSL::fatFSINFOStruct::fsinfoReserved2[12]"

.SS "uint32_t openFSL::fatFSINFOStruct::fsinfoSignature1"

.SS "uint32_t openFSL::fatFSINFOStruct::fsinfoSignature2"

.SS "uint32_t openFSL::fatFSINFOStruct::fsinfoSignature3"


.SH "Author"
.PP 
Generated automatically by Doxygen for OpenFSL from the source code\&.
