.TH "src/header/sector.h" 3 "Tue May 25 2021" "OpenFSL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/header/sector.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include 'fslservices\&.h'\fP
.br
\fC#include 'vint\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBopenFSL::Sector\fP"
.br
.RI "\fBSector\fP buffer\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBopenFSL\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenFSL from the source code\&.
