.TH "todo" 3 "Tue May 25 2021" "OpenFSL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBClass \fBopenFSL::DiskDevice\fP \fP" 1c
Write function wrapper 
.IP "\fBClass \fBopenFSL::FS_FAT32\fP \fP" 1c
File Read, Directory write, File write, FS format, UCS-2 Unicode Codepage 
.IP "\fBClass \fBopenFSL::Sector\fP \fP" 1c
Change buffer addressing process
.PP

