// This file is generated by bintoc. DO NOT MODIFY IT.

/* Copyright (c) 2021. kms1212(Minsu Kwon)
This file is part of OpenFSL.

OpenFSL and its source code is published over BSD 3-Clause License.
Check the full BSD-3-Clause license for more details.
<https://raw.githubusercontent.com/kms1212/OpenFSL/main/LICENSE>

*/

#ifndef OPENFSL_BOOTCODE_H_
#define OPENFSL_BOOTCODE_H_

extern unsigned long long _blob_mbrboot_bin_len;
extern unsigned char _blob_mbrboot_bin_data[];

extern const unsigned long long _blob_vbrboot_bin_len;
extern const unsigned char _blob_vbrboot_bin_data[];

#endif  // OPENFSL_BOOTCODE_H_
