name: Build

on: [push, pull_request]

env:
    BUILD_TYPE: Debug
    
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [x86, x64]
        os: [ ubuntu-latest, windows-latest ] # [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: '${{ matrix.os }}'
    name: '${{ matrix.os }}-${{ matrix.platform }}: build'
    steps:
    - uses: actions/checkout@v2
    - name: Install Required Software
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install cmake doxygen graphviz
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install cmake doxygen.install graphviz
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash
      
    - name: Configure CMake
      run: |
        cmake -S. -Bbuild -DBUILD_TESTING=true -DDOXYGEN_GENERATE=false
      shell: bash
      
    - name: Build
      run: |
        make VERBOSE=1
      shell: bash
      working-directory: ${{github.workspace}}/build
      
    - name: Test
      run: |
        ctest -C ${{env.BUILD_TYPE}}
      shell: bash
      working-directory: ${{github.workspace}}/build
