name: Doxygen

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]
        os: [ ubuntu-latest ]
        
    runs-on: '${{ matrix.os }}'
    
    name: 'Doxygen'

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Required Software
      run: |
          sudo apt-get update
          sudo apt-get install cmake doxygen graphviz git
      shell: bash

    - name: Configure CMake
      run: |
        cmake -B build -DDOXYGEN_GENERATE=true -DNO_BUILD=true
      shell: bash

    - name: Generate document
      run: |
        cmake --build build
      shell: bash
      
    - name: Prepare publishing to GH Page
      run: |
        git clone https://github.com/kms1212/kms1212.github.com
        mkdir -p ./kms1212.github.com/OpenFSL/doc/html
        cp ./doc/html/* ./kms1212.github.com/OpenFSL/doc/html/
        cd kms1212.github.com
        echo $
      shell: bash
      
    - name: Push to GH Page
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'kms1212.github.com'
        destination-github-username: 'kms1212'
        destination-repository-name: 'kms1212.github.com'
        user-email: kms1212g@gmail.com
        commit-message: OpenFSL Document update
        target-branch: main
