name: Deploy Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

env:
  BUILD_TYPE: Release
  
jobs:
  linux-x64-build:
    runs-on: 'ubuntu-latest'
    name: 'Linux-x64: Deploy'
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Required Software
      run: |
        sudo apt-get update
        sudo apt-get install cmake zip
      shell: bash
      
    - name: Create temp branch
      run: |
        git clone https://github.com/kms1212/OpenFSL/ ./packages
        cd ./packages
        git checkout --orphan release-temp
        rm -rf .gitignore .github .gitmodules
        rm -rf ./*
      shell: bash
      
    - name: Build & Test & Pack
      run: |
        cmake -G "Unix Makefiles" -S. -Bbuild \
              -DTARGET_ARCHITECTURE="AMD64" \
              -DBUILD_TESTING=true \
              -DDOXYGEN_GENERATE=false \
              -DNO_BUILD=false \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DPACKAGE_TYPE=NIGHTLY \
              -DPACKAGE_GENERATE=true \
              -DPACKAGE_GENERATOR=TGZ \
              -DBUILD_FAT32=true
        cmake --build build --target all test package
        
        cmake -G "Unix Makefiles" -S. -Bbuild \
              -DTARGET_ARCHITECTURE="AMD64" \
              -DBUILD_TESTING=true \
              -DDOXYGEN_GENERATE=false \
              -DNO_BUILD=false \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DPACKAGE_TYPE=NIGHTLY \
              -DPACKAGE_GENERATE=true \
              -DPACKAGE_GENERATOR=ZIP \
              -DBUILD_FAT32=true
        cmake --build build --target all test package
        
        cmake -G "Unix Makefiles" -S. -Bbuild \
              -DTARGET_ARCHITECTURE="AMD64" \
              -DBUILD_TESTING=true \
              -DDOXYGEN_GENERATE=false \
              -DNO_BUILD=false \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DPACKAGE_TYPE=NIGHTLY \
              -DPACKAGE_GENERATE=true \
              -DPACKAGE_GENERATOR=DEB \
              -DBUILD_FAT32=true
        cmake --build build --target all test package
        cp build/openfsl-* packages/
        
        cd packages
        git config --global user.email "kms1212g@gmail.com"
        git config --global user.name "kms1212"
        git add -A
        git commit -m "Update" -a
      shell: bash
      
    - name: Push to temporary branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        branch: release-temp
        directory: ./packages/
        
  linux-x86-build:
    needs: [linux-x64-build]
    runs-on: 'ubuntu-latest'
    name: 'Linux-x64: Deploy'
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Required Software
      run: |
        sudo apt-get update
        sudo apt-get install cmake zip
      shell: bash
      
    - name: Install Required Software
      run: |
        git clone https://github.com/kms1212/OpenFSL/ ./packages
        cd ./packages
        git checkout --orphan release-temp
        rm -rf .gitignore .github .gitmodules
        rm -rf ./*
      shell: bash
      
    - name: Build & Test & Pack
      run: |
        cmake -G "Unix Makefiles" -S. -Bbuild \
              -DTARGET_ARCHITECTURE="x86" \
              -DBUILD_TESTING=true \
              -DDOXYGEN_GENERATE=false \
              -DNO_BUILD=false \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DPACKAGE_TYPE=NIGHTLY \
              -DPACKAGE_GENERATE=true \
              -DPACKAGE_GENERATOR=TGZ \
              -DBUILD_FAT32=true
        cmake --build build --target all test package
        
        cmake -G "Unix Makefiles" -S. -Bbuild \
              -DTARGET_ARCHITECTURE="x86" \
              -DBUILD_TESTING=true \
              -DDOXYGEN_GENERATE=false \
              -DNO_BUILD=false \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DPACKAGE_TYPE=NIGHTLY \
              -DPACKAGE_GENERATE=true \
              -DPACKAGE_GENERATOR=ZIP \
              -DBUILD_FAT32=true
        cmake --build build --target all test package
        
        cmake -G "Unix Makefiles" -S. -Bbuild \
              -DTARGET_ARCHITECTURE="x86" \
              -DBUILD_TESTING=true \
              -DDOXYGEN_GENERATE=false \
              -DNO_BUILD=false \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DPACKAGE_TYPE=NIGHTLY \
              -DPACKAGE_GENERATE=true \
              -DPACKAGE_GENERATOR=DEB \
              -DBUILD_FAT32=true
        cmake --build build --target all test package
        cp build/openfsl-* packages/
        
        cd packages
        git config --global user.email "kms1212g@gmail.com"
        git config --global user.name "kms1212"
        git add -A
        git commit -m "Update" -a
      shell: bash
      
    - name: Push to temporary branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        branch: release-temp
        directory: ./packages/
        
  windows-x64-build:
    needs: [linux-x86-build]
    runs-on: 'windows-latest'
    name: 'Windows-x64: Deploy'
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Required Software
      run: |
        choco install cmake 7zip nsis
      shell: bash
      
    - name: Build & Test & Pack
      run: |
        git clone -b release-temp https://github.com/kms1212/OpenFSL/ ./packages
        
        cmake -G "Visual Studio 16 2019" -A x64 -S. -Bbuild \
              -DBUILD_TESTING=true \
              -DDOXYGEN_GENERATE=false \
              -DNO_BUILD=false \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DPACKAGE_TYPE=NIGHTLY \
              -DPACKAGE_GENERATE=true \
              -DPACKAGE_GENERATOR=TGZ \
              -DBUILD_FAT32=true
        cmake --build build --config ${{env.BUILD_TYPE}} --target all_build run_tests package
        
        cmake -G "Visual Studio 16 2019" -A x64 -S. -Bbuild \
              -DBUILD_TESTING=true \
              -DDOXYGEN_GENERATE=false \
              -DNO_BUILD=false \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DPACKAGE_TYPE=NIGHTLY \
              -DPACKAGE_GENERATE=true \
              -DPACKAGE_GENERATOR=ZIP \
              -DBUILD_FAT32=true
        cmake --build build --config ${{env.BUILD_TYPE}} --target all_build run_tests package
        
        cmake -G "Visual Studio 16 2019" -A x64 -S. -Bbuild \
              -DBUILD_TESTING=true \
              -DDOXYGEN_GENERATE=false \
              -DNO_BUILD=false \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DPACKAGE_TYPE=NIGHTLY \
              -DPACKAGE_GENERATE=true \
              -DPACKAGE_GENERATOR=NSIS64 \
              -DBUILD_FAT32=true
        cmake --build build --config ${{env.BUILD_TYPE}} --target all_build run_tests package
        cp build/openfsl-* packages/
        
        cd packages
        git config --global user.email "kms1212g@gmail.com"
        git config --global user.name "kms1212"
        git add -A
        git commit -m "Update" -a
      shell: bash
      
    - name: Push to temporary branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        branch: release-temp
        directory: ./packages/
        
        
  windows-x86-build:
    needs: [windows-x64-build]
    runs-on: 'windows-latest'
    name: 'Windows-x86: Deploy'
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Required Software
      run: |
        choco install cmake 7zip nsis
      shell: bash
      
    - name: Build & Test & Pack
      run: |
        git clone -b release-temp https://github.com/kms1212/OpenFSL/ ./packages
        
        cmake -G "Visual Studio 16 2019" -A Win32 -S. -Bbuild \
              -DBUILD_TESTING=true \
              -DDOXYGEN_GENERATE=true \
              -DNO_BUILD=false \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DPACKAGE_TYPE=NIGHTLY \
              -DPACKAGE_GENERATE=true \
              -DPACKAGE_GENERATOR=TGZ \
              -DBUILD_FAT32=true
        cmake --build build --config ${{env.BUILD_TYPE}} --target all_build run_tests package
        
        cmake -G "Visual Studio 16 2019" -A Win32 -S. -Bbuild \
              -DBUILD_TESTING=true \
              -DDOXYGEN_GENERATE=true \
              -DNO_BUILD=false \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DPACKAGE_TYPE=NIGHTLY \
              -DPACKAGE_GENERATE=true \
              -DPACKAGE_GENERATOR=ZIP \
              -DBUILD_FAT32=true
        cmake --build build --config ${{env.BUILD_TYPE}} --target all_build run_tests package
        
        cmake -G "Visual Studio 16 2019" -A Win32 -S. -Bbuild \
              -DBUILD_TESTING=true \
              -DDOXYGEN_GENERATE=true \
              -DNO_BUILD=false \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DPACKAGE_TYPE=NIGHTLY \
              -DPACKAGE_GENERATE=true \
              -DPACKAGE_GENERATOR=NSIS \
              -DBUILD_FAT32=true
        cmake --build build --config ${{env.BUILD_TYPE}} --target all_build run_tests package
        cp build/openfsl-* packages/
        
        cd packages
        git config --global user.email "kms1212g@gmail.com"
        git config --global user.name "kms1212"
        git add -A
        git commit -m "Update" -a
      shell: bash
      
    - name: Push to temporary branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        branch: release-temp
        directory: ./packages/
        
        
  macos-x64-build:
    needs: [windows-x86-build]
    runs-on: 'macos-latest'
    name: 'macOS-x64: Deploy'
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Required Software
      run: |
        brew install cmake p7zip make
      shell: bash
      
    - name: Build & Test & Pack
      run: |
        git clone -b release-temp https://github.com/kms1212/OpenFSL/ ./packages
        
        cmake -G "Unix Makefiles" -S. -Bbuild \
              -DTARGET_ARCHITECTURE="AMD64" \
              -DBUILD_TESTING=true \
              -DDOXYGEN_GENERATE=false \
              -DNO_BUILD=false \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DPACKAGE_TYPE=NIGHTLY \
              -DPACKAGE_GENERATE=true \
              -DPACKAGE_GENERATOR=TGZ \
              -DBUILD_FAT32=true
        cmake --build build --target all test package
        
        cmake -G "Unix Makefiles" -S. -Bbuild \
              -DTARGET_ARCHITECTURE="AMD64" \
              -DBUILD_TESTING=true \
              -DDOXYGEN_GENERATE=false \
              -DNO_BUILD=false \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DPACKAGE_TYPE=NIGHTLY \
              -DPACKAGE_GENERATE=true \
              -DPACKAGE_GENERATOR=ZIP \
              -DBUILD_FAT32=true
        cmake --build build --target all test package
        cp build/openfsl-* packages/
        
        cd packages
        git config --global user.email "kms1212g@gmail.com"
        git config --global user.name "kms1212"
        git add -A
        git commit -m "Update" -a
      shell: bash
      
    - name: Push to temporary branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        branch: release-temp
        directory: ./packages/
        
  release:
    needs: [macos-x64-build]
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Clone release-temp branch of OpenFSL
      run: |
        git clone -b release-temp https://github.com/kms1212/OpenFSL
      shell: bash
      
      
    - name: Update assets
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.API_TOKEN_GITHUB }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly build"
        files: |
          OpenFSL/*
          
    - name: Delete temporary branch
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        branches: release-temp