name: Deploy Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

env:
  BUILD_TYPE: Release
  
jobs:
  linux-x64-build:
    runs-on: 'ubuntu-latest'
    name: 'Linux-x64: Deploy'
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Required Software
      run: |
        sudo apt-get update
        sudo apt-get install cmake zip
      shell: bash
      
    - name: Build & Test & Pack
      run: |
        cmake -G "Unix Makefiles" -S. -Bbuild -DBUILD_TESTING=true -DDOXYGEN_GENERATE=false -DNO_BUILD=false -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPACKAGE_GENERATE=true -DPACKAGE_GENERATOR=TGZ
        cmake --build build
        cd build
        ctest -C ${{env.BUILD_TYPE}}
        cpack
        mkdir packages
        cd ..
        
        cmake -G "Unix Makefiles" -S. -Bbuild -DBUILD_TESTING=true -DDOXYGEN_GENERATE=false -DNO_BUILD=false -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPACKAGE_GENERATE=true -DPACKAGE_GENERATOR=ZIP
        cmake --build build
        cd build
        ctest -C ${{env.BUILD_TYPE}}
        cpack
        cd ..
        
        cmake -G "Unix Makefiles" -S. -Bbuild -DBUILD_TESTING=true -DDOXYGEN_GENERATE=false -DNO_BUILD=false -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPACKAGE_GENERATE=true -DPACKAGE_GENERATOR=DEB
        cmake --build build
        cd build
        ctest -C ${{env.BUILD_TYPE}}
        cpack
        cp OpenFSL-* packages/
      shell: bash
      
    - name: Push to temporary branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: release-temp
        folder: ./build/packages/
        token: ${{ secrets.API_TOKEN_GITHUB }}
        clean: false
        
        
  windows-x64-build:
    needs: [linux-x64-build]
    runs-on: 'windows-latest'
    name: 'Windows-x64: Deploy'
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Required Software
      run: |
        choco install cmake 7zip nsis
      shell: bash
      
    - name: Build & Test & Pack
      run: |
        cmake -G "Visual Studio 16 2019" -A x64 -S. -Bbuild -DBUILD_TESTING=true -DDOXYGEN_GENERATE=false -DNO_BUILD=false -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPACKAGE_GENERATE=true -DPACKAGE_GENERATOR=TGZ
        cmake --build build --config ${{env.BUILD_TYPE}}
        cd build
        ctest -C ${{env.BUILD_TYPE}}
        cpack
        mkdir packages
        cd ..
        
        cmake -G "Visual Studio 16 2019" -A x64 -S. -Bbuild -DBUILD_TESTING=true -DDOXYGEN_GENERATE=false -DNO_BUILD=false -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPACKAGE_GENERATE=true -DPACKAGE_GENERATOR=ZIP
        cmake --build build --config ${{env.BUILD_TYPE}}
        cd build
        ctest -C ${{env.BUILD_TYPE}}
        cpack
        cd ..
        
        cmake -G "Visual Studio 16 2019" -A x64 -S. -Bbuild -DBUILD_TESTING=true -DDOXYGEN_GENERATE=false -DNO_BUILD=false -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPACKAGE_GENERATE=true -DPACKAGE_GENERATOR=NSIS
        cmake --build build --config ${{env.BUILD_TYPE}}
        cd build
        ctest -C ${{env.BUILD_TYPE}}
        cpack
        cp OpenFSL-* packages/
      shell: bash
      
    - name: Push to temporary branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: release-temp
        folder: ./build/packages/
        token: ${{ secrets.API_TOKEN_GITHUB }}
        clean: false
        
        
  windows-x86-build:
    needs: [windows-x64-build]
    runs-on: 'windows-latest'
    name: 'Windows-x86: Deploy'
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Required Software
      run: |
        choco install cmake 7zip nsis
      shell: bash
      
    - name: Build & Test & Pack
      run: |
        cmake -G "Visual Studio 16 2019" -A Win32 -S. -Bbuild -DBUILD_TESTING=true -DDOXYGEN_GENERATE=false -DNO_BUILD=false -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPACKAGE_GENERATE=true -DPACKAGE_GENERATOR=TGZ
        cmake --build build --config ${{env.BUILD_TYPE}}
        cd build
        ctest -C ${{env.BUILD_TYPE}}
        cpack
        mkdir packages
        cd ..
        
        cmake -G "Visual Studio 16 2019" -A Win32 -S. -Bbuild -DBUILD_TESTING=true -DDOXYGEN_GENERATE=false -DNO_BUILD=false -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPACKAGE_GENERATE=true -DPACKAGE_GENERATOR=ZIP
        cmake --build build --config ${{env.BUILD_TYPE}}
        cd build
        ctest -C ${{env.BUILD_TYPE}}
        cpack
        cd ..
        
        cmake -G "Visual Studio 16 2019" -A Win32 -S. -Bbuild -DBUILD_TESTING=true -DDOXYGEN_GENERATE=false -DNO_BUILD=false -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPACKAGE_GENERATE=true -DPACKAGE_GENERATOR=NSIS
        cmake --build build --config ${{env.BUILD_TYPE}}
        cd build
        ctest -C ${{env.BUILD_TYPE}}
        cpack
        cp OpenFSL-* packages/
      shell: bash
      
    - name: Push to temporary branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: release-temp
        folder: ./build/packages/
        token: ${{ secrets.API_TOKEN_GITHUB }}
        clean: false
        
        
  macos-x64-build:
    needs: [windows-x86-build]
    runs-on: 'macos-latest'
    name: 'macOS-x64: Deploy'
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Required Software
      run: |
        brew install cmake p7zip make
      shell: bash
      
    - name: Build & Test & Pack
      run: |
        cmake -G "Unix Makefiles" -S. -Bbuild -DBUILD_TESTING=true -DDOXYGEN_GENERATE=false -DNO_BUILD=false -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPACKAGE_GENERATE=true -DPACKAGE_GENERATOR=TGZ
        cmake --build build
        cd build
        ctest -C ${{env.BUILD_TYPE}}
        cpack
        mkdir packages
        cd ..
        
        cmake -G "Unix Makefiles" -S. -Bbuild -DBUILD_TESTING=true -DDOXYGEN_GENERATE=false -DNO_BUILD=false -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPACKAGE_GENERATE=true -DPACKAGE_GENERATOR=ZIP
        cmake --build build
        cd build
        ctest -C ${{env.BUILD_TYPE}}
        cpack
        cp OpenFSL-* packages/
      shell: bash
      
    - name: Push to temporary branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: release-temp
        folder: ./build/packages/
        token: ${{ secrets.API_TOKEN_GITHUB }}
        clean: false
        
  release:
    needs: [build]
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Clone release-temp branch of OpenFSL
      run: |
        git clone -b release-temp https://github.com/kms1212/OpenFSL
      shell: bash
      
      
    - name: Update assets
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.API_TOKEN_GITHUB }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly build"
        files: |
          OpenFSL/*
          
    - name: Delete temporary branch
      run: |
        git branch -d release-temp
      shell: bash