name: Deploy Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

env:
  BUILD_TYPE: Release
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ x86, x64 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        pkg: [ ZIP, TGZ, DEB, NSIS ]
        exclude:
        - os: windows-latest
          pkg: DEB
        - os: ubuntu-latest
          pkg: NSIS
        - os: macos-latest
          pkg: DEB
        - os: macos-latest
          pkg: NSIS
        - os: ubuntu-latest
          platform: x86
        - os: macos-latest
          platform: x86
        
    runs-on: '${{ matrix.os }}'
    name: '${{ matrix.os }}-${{ matrix.platform }}-${{ matrix.pkg }}: Deploy'
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Required Software
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install cmake zip
        elif [ "$RUNNER_OS" == "Windows" ]; then
          choco install cmake 7zip nsis
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install cmake p7zip make
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash
      
    - name: Configure CMake
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          cmake -G "Unix Makefiles" -S. -Bbuild -DBUILD_TESTING=true -DDOXYGEN_GENERATE=false -DNO_BUILD=false -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPACKAGE_GENERATE=true -DPACKAGE_GENERATOR=${{matrix.pkg}}
        elif [ "$RUNNER_OS" == "Windows" ]; then
          if [ "${{matrix.platform}}" == "x86" ]; then
            cmake -G "Visual Studio 16 2019" -A Win32 -S. -Bbuild -DBUILD_TESTING=true -DDOXYGEN_GENERATE=false -DNO_BUILD=false -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPACKAGE_GENERATE=true -DPACKAGE_GENERATOR=${{matrix.pkg}}
          elif [ "${{matrix.platform}}" == "x64" ]; then
            cmake -G "Visual Studio 16 2019" -A x64 -S. -Bbuild -DBUILD_TESTING=true -DDOXYGEN_GENERATE=false -DNO_BUILD=false -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPACKAGE_GENERATE=true -DPACKAGE_GENERATOR=${{matrix.pkg}}
          else
            echo "${{matrix.platform}} not supported"
            exit 1
          fi
        elif [ "$RUNNER_OS" == "macOS" ]; then
          cmake -G "Unix Makefiles" -S. -Bbuild -DBUILD_TESTING=true -DDOXYGEN_GENERATE=false -Bbuild -DNO_BUILD=false -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPACKAGE_GENERATE=true -DPACKAGE_GENERATOR=${{matrix.pkg}}
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash
      
    - name: Build
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          cmake --build build
        elif [ "$RUNNER_OS" == "Windows" ]; then
          cmake --build build --config ${{env.BUILD_TYPE}}
        elif [ "$RUNNER_OS" == "macOS" ]; then
          cmake --build build
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
      shell: bash
      
    - name: Test
      run: |
        ctest -C ${{env.BUILD_TYPE}}
      shell: bash
      working-directory: ${{github.workspace}}/build
      
    - name: Make Package
      run: |
        cpack
        mkdir packages
        cp OpenFSL-* packages/
      shell: bash
      working-directory: ${{github.workspace}}/build
      
    - name: Push to temporary branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: release-temp
        folder: ./build/packages/
        token: ${{ secrets.API_TOKEN_GITHUB }}
        clean: true
        
  release:
    needs: [build]
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Clone release-temp branch of OpenFSL
      run: |
        git clone -b release-temp https://github.com/kms1212/OpenFSL
      shell: bash
      
      
    - name: Update assets
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.API_TOKEN_GITHUB }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly build"
        files: |
          OpenFSL/*
          
    - name: Delete temporary branch
      run: |
        git branch -d release-temp
      shell: bash